services:
  node-app:
    build: .
    container_name: multimatics-node
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mariadb
    environment:
      - DB_HOST=multimatics-db
      - DB_USER=root
      - DB_PASSWORD=rootsecret
      - DB_NAME=db_project
      - PORT=5001
    networks:
      - multimatics-network
  mariadb:
    image: mariadb:latest
    container_name: multimatics-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootsecret
      MARIADB_DATABASE: db_project
    ports:
      - "3396:3306"
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - multimatics-network

# volumes:
#   mariadb_data:

networks:
  multimatics-network:
